refactor(root): pre-commit - cannot commit into next & master branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -8,5 +8,10 @@
 #   exit 1
 # fi
 
+if [ "$branch" = "next" ]; then
+  echo "You can't commit directly to next branch"
+  exit 1
+fi
+
 make lint-staged
 make lint-staged-lib
